### ISSUE TITLE
vaultpropertysource is getting populated fine but the password from vault cannot be injected

### ISSUE THREAD

**Issue by manishrajkarnikar** [markramach/spring-boot-starter-vault#1]
I see that vaultpropertysource is getting populated with password from vault. But the secret cannot be injected into the bean. I tried 

```
 @Value('${path/to/secret}')
 String secret

```

Looks like my bean is getting initialized before the property source is getting populated with vault api

Do I need to set order somewhere?

**Comment by markramach** [comment]
@manishrajkarnikar It looks like you may be dealing with a property source ordering issue. Issue #3  documents the solutions available to you.

**Comment by manishrajkarnikar** [comment]
@markramach  I put all the config in bootstrap.yml instead of application.yml and everything works now. I should have read more on spring-cloud.
