### ISSUE TITLE
Please rename this artifact to conform to guidelines set out in Spring Boot user guide

### ISSUE THREAD

**Issue by dsyer** [markramach/spring-boot-starter-vault#2]
Thank you for your interest in the Spring Boot, and for publishing this code which looks very useful. Please can you change the artifact id to align with the suggested guidelines in the spring boot user guide (http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-custom-starter)?

**Comment by markramach** [comment]
Thank you for the comments and interest. I'll have the project renamed shortly.
