### ISSUE TITLE
Property injection does not work when used with Configserver via Eureka

### ISSUE THREAD

**Issue by restwzeasy** [markramach/spring-boot-starter-vault#3]
The property injection works fine in local application configuration mode, but not in configuration lookup via [Eureka.](http://cloud.spring.io/spring-cloud-netflix/)  Once we tried to integrate the setup into our environment where we are getting configurations from [configserver](http://cloud.spring.io/spring-cloud-config/) that is looked up via Eureka, attempts to contact Eureka to lookup configserver failed due to the Eureka URL containing unresolved parameters which need to be obtained from Vault prior to that point.

`( Example: http://${user}:${pass}..... )`

[More details on Stackoverflow](http://stackoverflow.com/questions/36368085/bootstrap-propertysource-ordering)

**Comment by markramach** [comment]
From the look of it, you seem to have found a work around. I was able to simply implement `Phased` on `VaultPropertySourceLocator` and order my property sources. However, it does require that you have some level of control over the ordering of all available property sources. I'm not sure this level of granular control will exist in all cases.
