### ISSUE TITLE
Insecure application bootup, information leakage

### ISSUE THREAD

**Issue by aabashkin** [markramach/spring-boot-starter-vault#4]
I believe there is an issue here:

"Also note that any configuration item can be specified on the command line when starting the Spring Boot application and is recommended if using token base authentication. For example:"

`java -jar spring-boot-app.jar --vault.token=0c6c3fce-09ee-72aa-fd5e-4d6f1152b002`

According to this [serverfault post](http://serverfault.com/questions/592744/how-to-hide-a-password-passed-as-command-line-argument) injecting the password through the command line will cause it show up in the process list (ps) thus exposing it to other local users.

The thread provides advice on how to recompile the program not to do this, but this seems extreme and in the case of the Java runtime I don't think we even have that option.

Perhaps we can brainstorm a new solution involving environment variables, similar to AWS: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment

**Comment by aabashkin** [comment]
Actually, environment variables present the same issue, they are interpreted and show up in `ps` the same way regular command line arguments do. I also realized this feature is already [present](https://www.vaultproject.io/docs/commands/environment.html)

AWS currently recommends the [profile approach](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles) where you are reading secrets from a file. This similar to the bootstrap.yml approach.Putting the key into a file mitigates the risk of it showing up in ps, and protects it from other local users through the use of file permissions. 

However, we still run into the problem of "secret zero" or "turtles all the way down". How do we manage that initial key/token which gives us access to everything else? We've added an extra step but it's really just a speedbump, not a wall.

I am currently testing a "process isolation" approach to mitigate this issue, I will keep everybody updated on progress

**Comment by markramach** [comment]
Firstly, I would recommend token based authentication for development purposes only. Setting the root token in the boostrap.yml file is a really bad idea for a number of reasons. Mainly, your root token potentially becomes part of your code base. 

I would definitely suggest using the documented app-id authentication option in a production environment. This utilizes a static application identifier, as well as a generated user id to authenticate with vault. If the byte code changes, the generated user id is no longer valid, preventing unauthorized code from accessing your secret store. Additionally, if the app-id is compromised you can revoke that app-id combination, not a token or potentially root token, disabling all other services using the token.

As far as other alternatives, like environment variables, or distributing secrets to a file on the host or container. If you are comfortable with the level of security implemented on your hosts, then you could take that approach.

However, I do think that app-id authentication is a much better cloud native solution.

**Comment by markramach** [comment]
@aabashkin I'm going to go ahead and close this issue. If you feel like you have another solution, feel free to submit a pull request.

**Comment by aabashkin** [comment]
Sure Mark. I'll open another thread if needed. A few comments from me for now:

I took another look at the docs of the App ID option to understand it better. Could you give some more detail on the statement "Typically the user ID is only available to the host running the application"?

The threat model I had in mind involves things like code injection and command injection, dynamic attacks that do not alter code/bytecode. Basically if the app id + user id is in the application's disk or memory space, can it be compromised through such attack vectors?

Your comment was " If the byte code changes, the generated user id is no longer valid, preventing unauthorized code from accessing your secret store" which I definitely agree with. The HMAC solution works great for maintaining integrity here. Does it cover other scenarios like the one described above with no byte-code change, just a compromised application?

Thanks again for the reply and interesting solution!
